config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    patch :toggle_status
  end

  devise_for :users

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  enum status: { draft: 0, published: 1 }

  validates :title, presence: true
  validates :status, inclusion: { in: Post.statuses.keys }

  has_rich_text :content

  def toggle_status!
    if draft?
      published!
    else
      draft!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :cofigure_permitted_parameters, if: :devise_controller?

  protected

  def cofigure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:idname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:idname])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  def index
    @posts = current_user.posts
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: '保存しました'
    else
      flash[:alert] = "問題が発生しました"
      render :new
    end
  end

  def show
    if @post.draft?
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to edit_post_path(@post), notice: '保存しました'
    else
      flash[:alert] = "問題が発生しました"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: '削除しました'
    else
      flash[:alert] = "問題が発生しました"
      render :post_path
    end
  end

  def toggle_status
    @post.toggle_status!
    redirect_to  posts_path, notice: '変更しました'
  end

  private

    def set_post
      @post = Post.find(params[:id] || params[:post_id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => 'shared/nav' %>
    <%= render :partial => 'shared/notification' %>

    <main role="main" class="container">

      <%= yield %>

    </main><!-- /.container -->
  </body>
</html>

app/views/pages/home.html.erb
  <div class="starter-template">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
  </div>

app/views/posts/edit.html.erb
<div class="col-md-8 mx-auto">
  <div class="mb-4">
    <h2 class="text-center">編集</h2>
    <%= form_with model: @post, local:true do |form| %>
      <div class="form-group">
        <%= form.label :title %>　<br />
        <%= form.text_field :title, class: "form-control"  %>
      </div>

      <div class="form-group">
        <%= form.label :content %><br />
        <%= form.rich_text_area :content %>
      </div>

      <hr>

      <div class="form-label-group col-md-6 mx-auto">
        <%= form.submit "更新", class: "btn btn-lg btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mx-auto">
      <div class="card">
        <div class="card-header">
          <h4>記事一覧</h4>
        </div>
        <div class="card-body">
          <% @posts.each do |post| %>
            <div class="row my-3">
              <div class="col-md-7">
                <h5><%= post.title %></h5>
              </div>
              <div class="col-md-2">
                <%= link_to post.status, post_toggle_status_path(post), method: :patch, class: "btn btn-outline-warning" %>
              </div>
              <div class="col-md-3">
                <%= link_to "表示", post_path(post), class: "btn btn-outline-primary float-left ml-1" %>　
                <%= link_to "編集", edit_post_path(post), class: "btn btn-outline-success float-left ml-1" %>
                <%= link_to "削除", post_path(post), method: :delete, class: "btn btn-outline-danger float-left ml-1" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-8 mx-auto">
  <div class="mb-4">
    <h2 class="text-center">新規投稿</h2>
    <%= form_with model: @post, local:true do |form| %>
        <div class="form-group">
          <%= form.label :title %>　<br />
          <%= form.text_field :title, class: "form-control"  %>
        </div>

        <div class="form-group">
          <%= form.label :content %><br />
          <%= form.rich_text_area :content %>
        </div>

        <hr>

        <div class="form-label-group col-md-6 mx-auto">
          <%= form.submit "登録", class: "btn btn-lg btn-primary btn-block" %>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 mx-auto">
  <h2><%= @post.title %></h2>
  <p>
    <%= @post.content %>
  </p>
</div>

app/views/shared/_nav.html.erb
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
      <% if (user_signed_in?) %>
        <%= link_to "Dashboard", posts_path, class: "top-link" %>
      <% else %>
      <a class="navbar-brand" href="/">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% end %>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <% if (!user_signed_in?) %>
            <li class="nav-item active">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %></a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <%= link_to "新規投稿", new_post_path, class: "dropdown-item" %>
                <%= link_to "編集", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_notification.html.erb
<% unless flash.empty?  %>
  <script>
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      new Noty({
          type: '<%= type %>',
          layout: 'topRight',
          timeout: 3000,
          theme: 'sunset',
          text: '<%= value %>'
      }).show();
    <% end %>
  </script>
<% end %>